### ISSUE TITLE
How to provide slots in stories?

### ISSUE THREAD

**Issue by galenwinsor** [storybookjs/addon-svelte-csf#104]
If I have a component with one or more slots, how do I declare them in the `<Template>` component?

**Comment by JReinhold** [comment]
I don't think you can spread slots natively in Svelte similar to how you can spread props, this is just how Svelte works. You need to define the slot content as you'd regular do with Svelte, either in the Template or in each story if you need to override it.

You can see an example here where the slot content for the button is both defined in the Template, and overwritten in a specific story.

https://github.com/storybookjs/addon-svelte-csf/blob/main/stories/button.stories.svelte

**Comment by galenwinsor** [comment]
Great, thanks!
