### ISSUE TITLE
[Bug] CanvasElement unknown type

### ISSUE THREAD

**Issue by StefanIlieP5** [storybookjs/addon-svelte-csf#105]
### Describe the bug

Svelte check throws errors when check interactions stories

### Steps to reproduce the behavior

1.Go to this
https://stackblitz.com/github/StefanIlieP5/svelte-storybook7

2. Run in console  pnpm check:svelte

### Expected behavior

canvasElement should have a known type

### Screenshots and/or logs

![image](https://github.com/storybookjs/addon-svelte-csf/assets/114990848/1c969bfe-26c7-41d2-8194-85f1e68611c9)

**Comment by bledeabogdan** [comment]
I'm wondering why the `Render` default type has `canvasElement` as `unknow` type by default? How do we properly specify the template type of the `StoryContext`. Have I missunderstood the usage of `play` function?

**Comment by shilman** [comment]
:rocket: Issue was released in [`v3.0.3`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v3.0.3) :rocket:
