### ISSUE TITLE
[Documentation] No clear/documented way to use Actions alongside svelte-addon-csf

### ISSUE THREAD

**Issue by kyleshepherd** [storybookjs/addon-svelte-csf#107]
There doesn't seem to be a documented way to use Actions alongside svelte-addon-csf. 

When using another Story format, you can set actions as shown [here](https://storybook.js.org/docs/svelte/essentials/actions). 

However, I'm unable to find documentation stating how to replicate this functionality when using the Svelte CSF addon.

Is this currently possible, and if so how do you get it working?

**Comment by JReinhold** [comment]
There's also an example here that uses a slightly different approach: https://github.com/storybookjs/addon-svelte-csf/blob/main/stories/addon-actions.stories.svelte

But I agree it could be documented better.

**Comment by j3rem1e** [comment]
Storybook should automatically subscribe to all discovered events for a Svelte Component. but something doesn't work here. probably because of the template proxy. 

I'll try to create an issue and fix it.

**Comment by shilman** [comment]
:rocket: Issue was released in [`v4.0.8`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v4.0.8) :rocket:
