### ISSUE TITLE
[Question] Jest support

### ISSUE THREAD

**Issue by angelmeraz** [storybookjs/addon-svelte-csf#11]
Is adding tests with jest supported?

I've got a setup already using `withTests` from `@storybook/addon-jest` with `*.stories.js` files but can't figure out how to add this onto my refactored stories using `*.stories.svelte`.

What I've tried so far:

```
// Button.stories.svelte
<script>
    import { Meta, Story, Template } from '@storybook/addon-svelte-csf';
    import results from '../.jest-test-results.json';
    import { withTests } from '@storybook/addon-jest';

    import Button from './Button.svelte';

    let count = 0;
    function handleClick() {
        count += 1;
    }
</script>

<Meta title="Button" component={Button} decorators={[withTests({ results })]} />

<Template let:args parameters={{ jest: ['Button.spec.js'] }}>
    <Button {...args} on:click={handleClick}>
        You clicked: {count}
    </Button>
</Template>

<Story name="Rounded" args={{rounded: true}}/>

<Story name="Square" source args={{rounded: false}}/>

<!-- Dynamic snippet should be disabled for this story -->
<Story name="Button No Args">
     <Button>Label</Button>
</Story>


// Button.spec.js
import '@testing-library/jest-dom/extend-expect';
import { render } from '@testing-library/svelte';
import Button from './Button.svelte';

describe('Button component', () => {
    test('renders correctly', () => {
        const component = render(Button, {
           rounded: true
        });

        expect(component).toMatchSnapshot();
    });
});
```

**Comment by j3rem1e** [comment]
This is theorically the right way to define a decorator. however.. I have never tested `addon-jest`, I don't know how it associates a story with a test. 

I'll add this to my todo list :)

**Comment by angelmeraz** [comment]
I guess the only other question would be, is there any other working method perhaps using a different jest add-on?

**Comment by j3rem1e** [comment]
I manage to make it works : 
- If you configure only the decorator, it will search a jest test with the same name as the story in the same folder: `Button.story.svelte` will search a `Button.test.js` or `Button.specs.js` (it's configurable with the `filesExt` property in the decorator)
- You can add a `parameters:jest` in the Meta tag or in a Story tag. It's not supported on the Template tag.  

```jsx
<Meta title="Button" 
  component={Button} 
  decorators={[withTests({ results })]} 
  parameters={{jest: ['Button.test.js']}}/>
```

Moreover, the `addon-jest` plugin doesn't seem to work with webpack5.
