### ISSUE TITLE
[Bug] Story control breaks at >= 14 each blocks

### ISSUE THREAD

**Issue by dancormier** [storybookjs/addon-svelte-csf#110]
### Describe the bug

Story controls stop working when 14 or more `each` blocks are within Story component.

### Steps to reproduce the behavior

1. Create a component that exports a prop and a `.story.svelte` to document the component
2. Add a `Story` component to your `.story.svelte` file
3. Add 14 or more [each blocks](https://svelte.dev/tutorial/each-blocks) within the `Story` component
4. Use the control on the story page and notice it has no affect

**Here's an example:**

#### Example.svelte
```svelte
<script lang="ts">
  export let disabled = false;
</script>

<div style={`background-color: ${disabled ? "#ccc" : "#0f0"}`}>
  <slot />
</div>
```

#### Example.story.svelte
```svelte
<script lang="ts">
  import { Meta, Story, Template } from "@storybook/addon-svelte-csf";
  import Example from "./Example.svelte";

  const items = Array.from(Array(5).keys());
</script>

<Meta title="Components/Example" component={Example} />

<Template let:args>
  <Example {...args}>Example element</Example>
</Template>

<Story name="Base" />

<Story name="Each">
  <ol>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
    <li>{#each items as item}{item}{/each}</li>
  </ol>
</Story>
```

### Expected behavior

I'd expect the controls to work regardless of the number of each blocks.

### Screenshots and/or logs

<details>
<summary>Story with 14 each blocks (control does not work)</summary>

![Story with 14 each blocks showing the control not working](https://github.com/storybookjs/addon-svelte-csf/assets/647177/01c9b57e-ca32-42a2-a082-017c92c01f74)

</details>

<details>
<summary>Story with 13 each blocks (control works)</summary>

![Story with 13 each blocks showing the control working](https://github.com/storybookjs/addon-svelte-csf/assets/647177/8ce57ad0-ad21-4763-969d-acd649a04ec7)

</details>

### Environment

 - OS: Mac OS 13.4.1
 - Node.js version: v18.15.0
 - NPM version: 9.5.0
 - Browser (if applicable): Firefox 114.0.2, Chrome 114.0.5735.106
 - Device (if applicable): MacBook Pro 16-inch, 2019

### Additional context

This issue was reported to me by a colleague that experienced the issue on their machine as well. cc @giamir

**Comment by j3rem1e** [comment]
https://github.com/sveltejs/svelte/issues/9203

**Comment by benmccann** [comment]
Thanks for the investigation! I'll close this in favor of the Svelte issue
