### ISSUE TITLE
How to use components with slot variable.

### ISSUE THREAD

**Issue by scorsi** [storybookjs/addon-svelte-csf#119]
Hello,

This title may be not clear... An example may be better:

I have this component which declares a slot and gives two slot variable which are in fact components
```svelte
<script lang="ts">
	import AvatarImage from './AvatarImage.svelte';
	import AvatarFallback from './AvatarFallback.svelte';
</script>
<div>
	<slot {AvatarImage} {AvatarFallback} />
</div>
```

We use it like so:
```svelte
<Avatar let:AvatarImage let:AvatarFallback>
	<AvatarImage src="https://randomuser.me/api/portraits/women/33.jpg" />
	<AvatarFallback>👩‍💻</AvatarFallback>
</Avatar>
```

I wonder how to use that inside the svelte addon because I tried multiple things and still got this error
```
this={...} of <svelte:component> should specify a Svelte component.
```
Here how I use it (which doesn't work)
```svelte
<Meta title="Avatar" component={Avatar} />

<Template let:args> <!-- also tried here -->
	<Avatar {...args} />
</Template>

<Story name="Example" let:AvatarImage let:AvatarFallback>
	<AvatarImage src="https://randomuser.me/api/portraits/women/33.jpg" />
	<AvatarFallback>👩‍💻</AvatarFallback>
</Story>
```

I guess it works similar has if it was:
```svelte
<script>
  let active = false;
</script>
<slot {active} />
```

**Comment by Tyneor** [comment]
Hello,

You have to use your <Avatar/> component in the Template or in the Story, like so :
```html
<Story name="Example">
  <Avatar let:AvatarImage let:AvatarFallback>
    <AvatarImage src="https://randomuser.me/api/portraits/women/33.jpg" />
    <AvatarFallback>👩‍💻</AvatarFallback>
  </Avatar>
</Story>
```
It worked on my side, hope this helps !

**Comment by benmccann** [comment]
It looks like this was answered

**Comment by scorsi** [comment]
> Hello,
> 
> You have to use your component in the Template or in the Story, like so :
> 
> ```
> <Story name="Example">
>   <Avatar let:AvatarImage let:AvatarFallback>
>     <AvatarImage src="https://randomuser.me/api/portraits/women/33.jpg" />
>     <AvatarFallback>👩‍💻</AvatarFallback>
>   </Avatar>
> </Story>
> ```
> 
> It worked on my side, hope this helps !

Thanks !
