### ISSUE TITLE
[Bug] Controls not connecting with UI

### ISSUE THREAD

**Issue by Nick-Mazuk** [storybookjs/addon-svelte-csf#12]
### Describe the bug

1. Updating a control does not update the component
2. When creating a story with preset args, it adds a duplicate control

More specifically in the story/component below, the "color" component is causing the issues.

### Steps to reproduce the behavior

Here's the story.

```svelte
<script>
    import { Meta, Template, Story } from '@storybook/addon-svelte-csf';
    import Badge from './badge.svelte';

    const meta = {
        title: "Badge",
        component: Badge,
        argTypes: {
            children: {
                control: {
                    type: 'text',
                },
                defaultValue: 'Hello world',
                name: 'children',
                type: { name: 'string', required: true }
            },
            size: {
                control: {
                    type: "select",
                    options: ['primary', 'secondary', 'error', 'highlight', 'warning', 'success'],
                },
                name: 'color',
                description: 'This is the color of the badge',
                type: { name: 'string', required: false }
            },
        },
     };

</script>

<Meta {...meta} />

<Template let:args>
  <Badge {...args}>{args.children}</Badge>
</Template>

<Story name="Default"/>

<Story name='With color' args={{color: 'primary'}} />
```

And here's the component.

```svelte
<script lang='ts'>
    type Color = 'primary' | 'secondary' | 'error' | 'highlight' | 'warning' | 'success'
    export let color: Color = 'secondary'

    const COLOR_MAP: Record<Color, string> = {
        primary: 'bg-primary',
        secondary: 'bg-secondary',
        // etc…
    }
</script>

<span class={`rounded ${COLOR_MAP[color]} font-semibold text-xs px-2 py-1`}>
    <slot></slot>
</span>
```

### Expected behavior

1. Updating a control via the UI updates the component
2. Setting a default value does not add an additional control

### Screenshots and/or logs

Here's the storybook: https://ui-svelte-9adyxhbbc-nick-mazuk.vercel.app/?path=/story/badge--default

### Environment

 - OS: macOS 11.2
 - Node.js version: v12.17.0
 - PNPM version: 5.18.8
 - Browser: Brave
 - Browser version: 1.21.77

### Additional context

I am brand new to Storybook, so it's possible that I'm just missing something obvious that I couldn't figure out. Though it doesn't look like this package is documented anywhere.

**Comment by j3rem1e** [comment]
I'll check that!

Does it works with the "standard" (js) CSF ?

**Comment by Nick-Mazuk** [comment]
> And why is the property called 'size' and not 'color' ?

That was it. Changing it from `size` to `color` fixed everything! Thanks for spotting that and sorry about the hassle.
