### ISSUE TITLE
[Bug] JSDoc prop descriptions aren't added to autodocs

### ISSUE THREAD

**Issue by Masstronaut** [storybookjs/addon-svelte-csf#122]
### Describe the bug

Svelte component props documented with the [officially recommended method](https://svelte.dev/docs/faq#how-do-i-document-my-components) - JSDoc comments - don't have their description added to the autodocs. Example:

```svelte
<script lang="ts">
	// Alert.svelte
	/** 
	 * The variant sets the styling of the alert.
	 * Use `Alert` variants to provide additional context to the user about the alert information. */
	export let variant: AlertVariant | undefined = undefined;
</script>
```

Elsewhere in VSCode - including in `*.stories.svelte` files - this comment shows up as a tooltip for the `variant` prop of the `Alert` component. You can see in this screenshot that hovering over `variant` on an `Alert` component causes the tooltip and description to appear:

![image](https://github.com/storybookjs/addon-svelte-csf/assets/9017393/698c72e4-1115-47af-bc59-47d48470373d)

However, in my autodocs for the `Alert` component, the description for the `variant` prop is not present:

![image](https://github.com/storybookjs/addon-svelte-csf/assets/9017393/be8c5de7-9f28-4acb-afba-00a67228afbe)

### Steps to reproduce the behavior

1. Create a svelte component with a prop that has a JSDoc comment describing it
2. enable autodocs globally for the project since it can't be specified on a per-component level with svelte-csf (See #87 )
3. create a svelte CSF story for the component
4. run storybook and look at the generated autodocs for it. Note that the prop documentation is not present.

### Expected behavior

Prop comments should be included in the appropriate place in autodocs

### Screenshots and/or logs

See screenshots above

### Environment

 - OS: Mac OS
 - Node.js version: v20.5.0
 - NPM version: 9.8.0
 - Browser (if applicable): n/a
 - Browser version (if applicable): n/a
 - Device (if applicable): n/a

**Comment by JReinhold** [comment]
This is unrelated to this addon, but actually a problem in Storybook's doc parsing not supporting TypeScript. Check out https://github.com/storybookjs/storybook/issues/15891 which describes why and a potential workaround.

Closing in favor of https://github.com/storybookjs/storybook/issues/15891
