### ISSUE TITLE
[Feature Request] Support autotitle

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/addon-svelte-csf#129]
Storybook has a feature called autotitle, that sets the title of the component (meta) based on the file path, if no title is explicitly set. It would be nice if this addon supported that feature.

### Implementation

The indexer gets passed a `makeTitle` function in the indexer options (second parameter) to the `indexer` function. That function can be used to generate this title automatically, also taking into account any user title specified.

### Additional context

Implementing this with `makeTitle` would probably also solve the bug at #130 at the same time.

**Comment by benmccann** [comment]
https://github.com/storybookjs/addon-svelte-csf/issues/101 sounds potentially related as well

**Comment by j3rem1e** [comment]
This API didn't exist when I have implemented the indexer. I can have a look at it.

**Comment by j3rem1e** [comment]
I have fixed autotitle here: https://github.com/storybookjs/addon-svelte-csf/pull/134
