### ISSUE TITLE
Issue template should ask for version of Storybook and `addon-svelte-csf` that are being used

### ISSUE THREAD

**Issue by benmccann** [storybookjs/addon-svelte-csf#141]
I noticed in https://github.com/storybookjs/addon-svelte-csf/issues/114#issue-1814593017 that it's unclear what versions are being used. It's possible the issue is already fixed, but I can't tell without setting up a whole project to test it. If I go to create a new issue the "Environment" section asks for a bunch of info, but not these important pieces. Maybe we should ask users to run `npx envinfo --system --binaries --browsers --npmPackages "{storybook,@storybook/*,vite,webpack,svelte,@sveltejs/*}"`. I'm not sure where this is configured though

**Comment by j3rem1e** [comment]
We shoukd probably use the "default" storybook template ? https://github.com/storybookjs/storybook/blob/next/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1

**Comment by benmccann** [comment]
I think the issue is that https://github.com/storybookjs/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md is used currently. If the version on `master` were updated to match what was on `next` it would address this

**Comment by benmccann** [comment]
I guess I'll just go ahead and close this because assuming that the `next` version is eventually promoted then this will be fixed
