### ISSUE TITLE
Unable to set slot description or default value

### ISSUE THREAD

**Issue by RavenX86** [storybookjs/addon-svelte-csf#146]
I am not sure if this is the right repo to ask this but the svelte parse automatically detects the slots and named slots inside the component, but there seems virtually no way to set the description for it, make int control text, or use said value in the template. I tried creating an argType default with category slots, but instead of overriding the autogenerated one, it creates it beneath it.

![CleanShot 2023-10-12 at 19 42 17@2x](https://github.com/storybookjs/addon-svelte-csf/assets/89336014/be6fd3c4-b615-470f-9a5d-0526a7f52c63)

![CleanShot 2023-10-12 at 19 52 36@2x](https://github.com/storybookjs/addon-svelte-csf/assets/89336014/43ccfe88-7f77-4ec3-a303-447986f111df)

**Comment by j3rem1e** [comment]
You can see an example here : https://github.com/alexprey/sveltedoc-parser/blob/dev/examples/SlotList.svelte
