### ISSUE TITLE
[Bug] Autodocs does not render Component name properly.

### ISSUE THREAD

**Issue by jenniferworrall** [storybookjs/addon-svelte-csf#151]
### Describe the bug

We have a sveltekit project with Storybook 7, and are using autodocs to generate our documentation.  Everything works except that the "Show Code" window shows <Proxy<RenderContext> instead of the actual component name.

Story:
```code
<script context="module">
	import { Template, Story } from '@storybook/addon-svelte-csf';
	import Icon from '$lib/buildingBlocks/Icon.svelte';

	export const meta = {
		title: 'Building Blocks / Icon',
		component: Icon,
		argTypes: {
			id: {
				control: { type: 'text' }
			},
			type: {
				options: ['external'],
				control: { type: 'select' }
			},
			size: {
				options: ['sm', 'md', 'lg'],
				control: { type: 'radio' }
			},
			inheritSize: {
				type: 'boolean',
				control: { type: 'boolean' }
			}
		},
		tags: ['autodocs']
	};
</script>

<Template let:args>
	<Icon {...args} />
</Template>

<Story
	name="Icon Tester"
	args={{ type: 'external', size: 'md', inheritSize: false }}
/>
```

### Steps to reproduce the behavior

1. Create story with autodocs on.  Go to generated docs
2. Click on "Show code"

### Expected behavior

Expect to see "<Icon" where "<Proxy<RenderedContext>" appears

### Screenshots and/or logs
![Screen Shot 2023-10-27 at 3 38 10 PM](https://github.com/storybookjs/addon-svelte-csf/assets/6393385/7eaf5d6d-0112-40b4-8124-b009907b3ffe)

### Environment

 - OS: MacOS
 - Node.js version: 18.17.1
 - NPM version: 9.6.7

**Comment by j3rem1e** [comment]
What version of storybook/this addon are you using ?

**Comment by jenniferworrall** [comment]
> What version of storybook/this addon are you using ?

We are using version 7.4.6 of storybook and 4.0.9 of this plug-in.  Thank you!

**Comment by j3rem1e** [comment]
This issue has been fixed in storybook v7.5.0 through https://github.com/storybookjs/storybook/issues/24008

**Comment by j3rem1e** [comment]
btw you don't have to define argTypes, they should be automatically inferred by storybook.

**Comment by jenniferworrall** [comment]
I just upgraded to 7.5.2 and no joy.  I also deleted package-lock.json and node_modules just to be sure and verified the behavior.  I was looking at the previous issue and thought I'd try removing let:args from the Template and when I do that, it does in fact work.

I can add this to the storybook repo instead though, doesn't seem to be an issue of the addon-svelte-csf package.

**Comment by j3rem1e** [comment]
Do you have a repo where I can check ?

Storybook, when it parses the component for extracting the documentation/argTypes, add a hidden property with the component name deduced from the file location. This property is used to generate the source snippet. If the property is not present, then it will try to generate a component name from the javascript constructor.

However, when Storybook is in dev mode, it activates Svelte HMR which replace the class by a Proxy (for reloading/keeping states/etc).

So you can see Proxy as the component name when:
* Storybook is in dev mode
* The component couldn't parsed

However, in sb 7.5, the hidden property should always be present, even if the composant is not valid.

**Comment by jenniferworrall** [comment]
Ah that makes sense!  I was going to update this story today to say that it
works great when the story is built but it doesn't work locally on our
machines, and that's because it's in the dev mode.  Thank you so much for
getting back to me.   I will pass this on to others on my team.

**Comment by Justin-wei** [comment]
I'm using "storybook": "^7.6.4","@storybook/addon-svelte-csf": "^4.0.13",

and I am using the template
<Template let:args>
  <Page {...args} />
</Template>

I still having this issue.
