### ISSUE TITLE
[Bug] Support for `svelte 5`

### ISSUE THREAD

**Issue by bhvngt** [storybookjs/addon-svelte-csf#156]
### Describe the bug
When I try to run this plugin with [svelte 5](https://github.com/sveltejs/svelte/releases/tag/svelte%405.0.0-next.4), it reports following error.

```
WARN 🚨 Unable to index files:
[SB] WARN - ./src/lib/Button/Button.stories.svelte: Cannot read properties of undefined (reading 'instance')
[SB] WARN - ./src/lib/Image/Image.stories.svelte: Cannot read properties of undefined (reading 'instance')
[SB] WARN - ./src/lib/Counter/Counter.stories.svelte: Cannot read properties of undefined (reading 'instance')
```

### Steps to reproduce the behavior

1. Upgrade `svelte` to `svelte@next`
2. run `storybook`
3. See error

### Expected behavior

It should work with svelte 5

### Environment

 - OS: [e.g. iOS] `OSX 14.0`
 - Node.js version: [e.g. v12.17.0] `20.9`
 - NPM version: [e.g. 6.14.4] pnpm `8.10.5`
 - Browser (if applicable): [e.g. chrome, safari]: chrome
 - Browser version (if applicable): [e.g. 22]: 119

### Additional context

Svelte 5 is cutting edge and is very new. So just filing this bug in case if it is a minor change to support it.

**Comment by j3rem1e** [comment]
I'm not sure Storybook itself supports Svelte 5 🙂

**Comment by bhvngt** [comment]
Svelte 5 is backward compatible with svelte 4. So I was trying to upgrade svelte without trying out any of the new svelte 5 syntax.

**Comment by JReinhold** [comment]
Here's the upstream issue: https://github.com/storybookjs/storybook/issues/24886

(might not be the same problem though)

**Comment by JReinhold** [comment]
We've added preliminary Svelte 5 support in the Storybook 8 alphas, you could try upgrading to those and see if that fixes the issue. If it does I think we can close it.

`npx storybook@next upgrade --prerelease` 

Based on the errors you've reported it looks like a Storybook core issue and not related to this addon.

**Comment by ryu-man** [comment]
I got this error using storybook 8 with svelte 5 installed
```
Unable to index ./src/stories/Test.stories.svelte:
WARN   TypeError: Cannot read properties of undefined (reading 'instance')
```

**Comment by eunukasiko** [comment]
```
- ./src/lib/components/button/Button.stories.svelte: Cannot read properties of undefined (reading 'instance')
```

**Comment by bhvngt** [comment]
I tried this plugin on the latest [8.0.0-rc.2](https://github.com/storybookjs/storybook/releases/tag/v8.0.0-rc.2) release which supports svelte 5. I have used the latest [4.1.2](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v4.1.2) for my reproduction.

I am getting the same error as @eunukasiko.

Here's the [link](https://codesandbox.io/p/devbox/storybook-svelte-5-gqg2wm?file=%2Fpackage.json%3A5%2C34) to the sandbox.

**Comment by RobinKnipe** [comment]
SB v8 now released. Would be great if Svelte5 were supported.

**Comment by bhvngt** [comment]
Since svelte 5 has reached [release-candidate](https://svelte.dev/blog/svelte-5-release-candidate). Would this be a good time to add support for svelte 5?

This add-on makes story creation for svelte so much easier. So thanks a ton to all the contributors for creating this add-on. 👏👏👏

**Comment by eunukasiko** [comment]
Yes. At least give an update - is support planned at all or should I start rewriting all stories without CSF?

**Comment by xeho91** [comment]
There's a work in progress #177

**Comment by xeho91** [comment]
The `next` version of this tag supports Svelte 5.
