### ISSUE TITLE
Svelte properties typed?

### ISSUE THREAD

**Issue by frederikhors** [storybookjs/addon-svelte-csf#17]
I'm using the code from https://github.com/storybookjs/addon-svelte-csf/blob/main/stories/button.stories.svelte but in my Storybook these properties are not typed: I can only use JSON strings, why?

![image](https://user-images.githubusercontent.com/41120635/112889858-7b3e1780-90d6-11eb-8af5-e45775ca415e.png)

**Comment by alexanderniebuhr** [comment]
you need to set argTypes in Meta

```svelte
<Meta
  title="Example/Button"
  component={Button}
  argTypes={{
    label: { control: "text" },
    primary: { control: "boolean" },
    backgroundColor: { control: "color" },
    size: {
      control: { type: "select", options: ["small", "medium", "large"] },
    },
    onClick: { action: "onClick" },
  }}
/>
```

**Comment by j3rem1e** [comment]
or it uses JSDoc to extract types. See the example in the storybook repo. it's not related to this addon.

**Comment by frederikhors** [comment]
And what if my `Button.svelte` is a "`<script lang="ts">`" file?

Can I infer types from that code?

Example:

```svelte
<script lang="ts">
  let className: string | undefined = undefined;
  export { className as class };

  export let red: boolean | undefined = undefined;
</script>

<button>...</button>
```

**Comment by j3rem1e** [comment]
It uses sveltedoc-parser which doesn't support typescript yet. so if the type can't be determined by the default value, you have to use jsdoc. it allows you to auto document your properties, slots and events too.

**Comment by frederikhors** [comment]
It works amazing! AMAZING! Thanks again!

**Comment by austinknight** [comment]
It seems that using jsdoc when there are any typed variables in a typescript svelte component, jsdoc doesn't work anymore. Does something override jsdoc when typescript is in use?

if I do this with ts, my storybook controls don't auto generate
```
/**
 * @type {('primary' | 'secondary' | 'tertiary' | 'danger')} Specify the Button variant
*/
export let variant: 'primary' | 'secondary' | 'tertiary' | 'danger' = 'primary';
```

But, if I remove types like this, it works
```
/**
 * @type {('primary' | 'secondary' | 'tertiary' | 'danger')} Specify the Button variant
*/
    export let variant = 'primary';
```
