### ISSUE TITLE
[Question/Documentation] How to use with MDX?

### ISSUE THREAD

**Issue by rChaoz** [storybookjs/addon-svelte-csf#176]
How to include stories defined in a `x.stories.svelte` in a MDX file?

```js
import Stories from "./Component.stories.svelte"
```

The following methods all include the first story defined in the stories file:

```js
<Canvas />
<Story />
```

I don't know what to set the `of` property to (`Stories.Name` doesn't work).

**Comment by rChaoz** [comment]
**Update:** apparently I was using `import Stories` instead of the one I should use: `import * as Stories`.
With the latter it works to use `<Story of={Stories.Primary} />` (or any named story), although the IDE is giving me "Unresolved variable" warnings.

**Comment by matths** [comment]
and do you know of a way to set different viewports in mdx?
