### ISSUE TITLE
Object literal may only specify known properties, and '"args"' does not exist in type 'StoryProps'

### ISSUE THREAD

**Issue by gzimbron** [storybookjs/addon-svelte-csf#196]
Hello, I'm using Storybook in a new project, and I'm getting this typescript error on vscode:
```
Object literal may only specify known properties, and '"args"' does not exist in type 'StoryProps'
```

![CleanShot 2024-08-02 at 09 31 29](https://github.com/user-attachments/assets/7a5cc4e6-4a80-4255-b579-b833961d8255)

Dependencies versions:
```
	"@storybook/addon-essentials": "8.2.7",
    "@storybook/addon-interactions": "8.2.7",
    "@storybook/addon-links": "8.2.7",
    "@storybook/addon-styling-webpack": "^1.0.0",
    "@storybook/addon-svelte-csf": "^4.1.4",
    "@storybook/blocks": "8.2.7",
    "@storybook/svelte": "8.2.7",
    "@storybook/sveltekit": "8.2.7",
    "@storybook/test": "8.2.7",
```

I have another project, and this warning doesn't appear, versions in other project are:
```
		"@storybook/addon-essentials": "^7.6.16",
		"@storybook/addon-interactions": "^7.6.16",
		"@storybook/addon-links": "^7.6.16",
		"@storybook/addon-svelte-csf": "^4.0.0",
		"@storybook/blocks": "^7.6.16",
		"@storybook/svelte": "^7.6.16",
		"@storybook/sveltekit": "^7.6.16",
		"@storybook/testing-library": "^0.0.14-next.2",
```
  
### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Environment

 - OS: MacOs
 - Node.js version: v20.16.0
 - NPM version: 10.8.1

**Comment by is-sematell** [comment]
Facing the same issue

**Comment by is-sematell** [comment]
I've updated all packages to the latest versions, and this issue does not reproduce anymore
