### ISSUE TITLE
[next] TODO: Replace script `context="module"` attribute with `module`

### ISSUE THREAD

**Issue by xeho91** [storybookjs/addon-svelte-csf#204]
There has been a breaking change in Svelte `v5`.

To summarise:

```diff
-<script context="module">
+<script module>
```

Reference: https://github.com/sveltejs/svelte/pull/12948

---

- [x] Update documentation 
- [x] Update AST parser/transformer

**Comment by shilman** [comment]
:rocket: Issue was released in [`v5.0.0-next.7`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v5.0.0-next.7) :rocket:
