### ISSUE TITLE
[Request] Svelte 5: <Template> support

### ISSUE THREAD

**Issue by viktorgullmark** [storybookjs/addon-svelte-csf#220]
Hey,

We're currently trying to migrate to Svelte 5, and are having problems with our previous stories that keep multiple templates in one file, since the deprecated `<Template>` component is still missing. 

I just wanted to ask if we are supposed to implement templates differently now, or if this component (or a similar one) will be reinstated? 

Tried tinkering with my own component but having problems passing `args` properly, since the old way with `let:args` is no longer valid.

Thanks!

**Comment by xeho91** [comment]
> We're currently trying to migrate to Svelte 5, and are having problems with our previous stories that keep multiple templates in one file, since the deprecated `<Template>` component is still missing.

We've created an opt-in [Legacy API support](https://github.com/storybookjs/addon-svelte-csf/tree/next?tab=readme-ov-file#legacy-api).

It should cover multiple `<Template>` component used in one file.
If you encountered a case where it doesn't work, we would appreciate a bug report with details such as error messages.

> I just wanted to ask if we are supposed to implement templates differently now, or if this component (or a similar one) will be reinstated?

As far we explored, there was no need to keep this component or reinstate it. For the following reasons:
1. [Svelte Snippets](https://svelte.dev/docs/svelte/snippet#Snippet-scope) does exactly what `<Template>` used to do, and the API is very similar.
2. `let:*` directives are deprecated
3. Snippets are more flexible

We provide a quick [migration guide](https://github.com/storybookjs/addon-svelte-csf/blob/next/MIGRATION.md#template-component-removed) for the deprecated `<Template>` component.

Also, the new API for [defining stories](https://svelte.dev/docs/svelte/snippet#Snippet-scope) is documented in the `next` branch README file.

> Tried tinkering with my own component but having problems passing `args` properly since the old way with `let:args` is no longer valid.

Could you check if opt-in legacy API support did help?
And if it did not... do you mind sharing what did you tried to achieve?

**Comment by viktorgullmark** [comment]
Thanks for the thorough response @xeho91!

> > We're currently trying to migrate to Svelte 5, and are having problems with our previous stories that keep multiple templates in one file, since the deprecated `<Template>` component is still missing.
> 
> We've created an opt-in [Legacy API support](https://github.com/storybookjs/addon-svelte-csf/tree/next?tab=readme-ov-file#legacy-api).
> 
> It should cover multiple legacy `<Template>` components used in one file. If you encountered a case where it doesn't work, we would appreciate a bug report with details such as error messages.
> 

I had no idea about the legacy API support, will make sure to try it, should be enough for us until we have time to convert the stories to the new API.

> > I just wanted to ask if we are supposed to implement templates differently now, or if this component (or a similar one) will be reinstated?
> 
> As far we explored, there was no need to keep this component or reinstate it. For the following reasons:
> 
> 1. [Svelte Snippets](https://svelte.dev/docs/svelte/snippet#Snippet-scope) does exactly what `<Template>` used to do, and the API is very similar.
> 2. `let:*` directives are deprecated
> 3. Snippets are more flexible
>
> We provide a quick [migration guide](https://github.com/storybookjs/addon-svelte-csf/blob/next/MIGRATION.md#template-component-removed) for the deprecated `<Template>` component.
> 

Thanks a lot for this, not sure how I missed it, will make sure to try this for a few of our stories.

> Also, the new API for [defining stories](https://github.com/storybookjs/addon-svelte-csf/blob/next/README.md#defining-stories) is documented in the `next` branch README file.
> 
> > Tried tinkering with my own component but having problems passing `args` properly since the old way with `let:args` is no longer valid.
> 
> Could you check if opt-in legacy API support did help? And if it did not... do you mind sharing what did you tried to achieve?

I'll let you know how things go. Again, thanks for the response and the links, will help me massively. I'll close this for now and re-open if I struggle with anything related to this!
