### ISSUE TITLE
[Bug] Legacy Template adds extra indent to template literal strings

### ISSUE THREAD

**Issue by olafurw** [storybookjs/addon-svelte-csf#227]
### Describe the bug

When using the `legacyTemplate` option, extra spaces are added to a template literal string. This breaks storybook stories that use for example template literal strings to set markdown text. These extra spaces are not added to the normal component.

### Steps to reproduce the behavior

https://github.com/olafurw/svelte-storybook-indent-bug

Clone this repo, run `npm run storybook` and to go the `Test` story.

### Expected behavior

No indent, like the normal component.

### Screenshots and/or logs

![Image](https://github.com/user-attachments/assets/cb588788-0acc-45f3-b52f-518b5fe1e890)

### Environment

 - OS: Ubuntu 24
 - Node.js version: 20.18.0
 - NPM version: 10.8.2
 - Browser (if applicable): Firefox
 - Browser version (if applicable): 131
 - Device (if applicable): Desktop

**Comment by xeho91** [comment]
Hi, thanks for nicely prepared bug report! ❤ 

The issue is on [`svelte-ast-print`](https://github.com/xeho91/svelte-ast-print) and when I catch some free time, I'll try to figure out how to solve your case.

**Comment by xeho91** [comment]
@olafurw I believe I solved your issue. I used your reproduction repository to test it out.
What you can do is reinstall dependencies with your package manager - `svelte-ast-print` should be upgraded to `0.4.2`.

Unless I overlooked something, then please do let me know and we can reopen this issue.
