### ISSUE TITLE
[Bug] Typescript support - types in Args<typeof Story> are optional when types of the Component aren't

### ISSUE THREAD

**Issue by fivaz3** [storybookjs/addon-svelte-csf#232]
### Describe the bug

Typescript support - types in Args<typeof Story> are optional when types of the Component aren't

### Steps to reproduce the behavior

create a clean Sveltekit project with TS 

`npx sv create my-app`

add storybook to the project

`npx storybook@latest init`

then go to the story file `src/stories/Button.stories.svelte` that comes with the storybook installation

and add a template with the typing like it's shown in this lib's readme:

```
<script module lang="ts">
    import {type Args, defineMeta,setTemplate} from '@storybook/addon-svelte-csf';
</script>
```

```
<script>
    setTemplate(template);
</script>

{#snippet template(args: Args<typeof Story>)}
    <div>
        <Button {...args}/>
    </div>
{/snippet}

```

then run the check command from package.json

> 
> Svelte: Type
> {     
>   primary?: boolean;     
>   backgroundColor?: string;     
>   size?: "small" | "medium" | "large";     
>   label?: string | undefined;     
>   onClick?: () => void; 
> }
> 
> is not assignable to type Props
> Types of property label are incompatible.
> Type string | undefined is not assignable to type string
> Type undefined is not assignable to type string
> 

### Expected behavior

this error shouldn't exist, or at least it should be addressed in the docs how to avoid it

### Screenshots and/or logs

![Image](https://github.com/user-attachments/assets/fff5f492-096b-45a5-a199-22b3426dcfd0)

**Comment by xeho91** [comment]
Hi, sorry you're encountering this issue. Is known one and a duplicate of #216. There's a temporary workaround in this issue.

We're in the process of rethinking the `setTemplate` API _(discussion on the channel for Svelte in Storybook Discord)_, and along with it those type helpers - `Args` & `StoryContext`.

**Comment by fivaz3** [comment]
No problem, I will follow the progress on the other issue and close this one. Despite the issue, congratulations on this amazing library!
