### ISSUE TITLE
[Bug] - Bug with Vite 6 and @sveltejs/vite-plugin-svelte v5

### ISSUE THREAD

**Issue by squelix** [storybookjs/addon-svelte-csf#238]
### Describe the bug

All the stories are bugged and does not work.

### Steps to reproduce the behavior

1. Start storybook in watch mode
2. The error occurs on every stories

### Expected behavior

It should starts the Storybook with no error.

### Screenshots and/or logs

![Image](https://github.com/user-attachments/assets/97f8b6c1-3586-4455-9eb8-2d57644cfa1f)

### Environment

- @storybook/addon-svelte-csf: v5.0.0-next.13
- vite: 6.0.1
- @sveltejs/vite-plugin-svelte: 5.0.1

 - OS: MacO
 - Node.js version: 22.11.0
 - Yarn version: 4.5.2
 - Browser (if applicable): chrome
 - Device (if applicable): MacbookPro

**Comment by xeho91** [comment]
Which version of Storybook are you using?

Could be related to the fact that Vite `v6` support for Storybook **core** currently is available in the [prerelease of `v8.5`](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.prerelease.md#850-alpha11).

**Comment by yannbf** [comment]
Hey there, as soon as we release a new Storybook patch as @xeho91 stated, can you please try it out? This issue should hopefully be resolved.

**Comment by JReinhold** [comment]
8.4.6 is released with Vite 6 support. 🎉

https://github.com/storybookjs/storybook/releases/tag/v8.4.6

**Comment by umaranis** [comment]
Hi team,
Even with storybook v8.4.0, I am getting the error.

```
WARN 🚨 Unable to index files:
WARN - ./src/stories/Button.stories.svelte: Cannot read properties of undefined (reading 'warningFilter')
WARN - ./src/stories/Header.stories.svelte: Cannot read properties of undefined (reading 'warningFilter')
WARN - ./src/stories/Page.stories.svelte: Cannot read properties of undefined (reading 'warningFilter')
The request url "/Users/umar/Documents/Projects/lexical/svelte-lexical/node_modules/.pnpm/vite@5.4.10_@types+node@22.7.4/node_modules/vite/dist/client/env.mjs" is outside of Vite serving allow list.
```

**Comment by xeho91** [comment]
> Hi team,
> Even with storybook v8.4.0, I am getting the error.
> 
> ```
> WARN 🚨 Unable to index files:
> WARN - ./src/stories/Button.stories.svelte: Cannot read properties of undefined (reading 'warningFilter')
> WARN - ./src/stories/Header.stories.svelte: Cannot read properties of undefined (reading 'warningFilter')
> WARN - ./src/stories/Page.stories.svelte: Cannot read properties of undefined (reading 'warningFilter')
> The request url "/Users/umar/Documents/Projects/lexical/svelte-lexical/node_modules/.pnpm/vite@5.4.10_@types+node@22.7.4/node_modules/vite/dist/client/env.mjs" is outside of Vite serving allow list.
> ```

See [this comment](https://github.com/storybookjs/addon-svelte-csf/issues/238#issuecomment-2506917459)

**Comment by umaranis** [comment]
HI @xeho91 ,

Getting the same error with `v8.4.6` as well.

Here are the dependencies:

```json
{
    "@chromatic-com/storybook": "^3.2.2",
    "@fontsource/fira-mono": "^5.1.0",
    "@neoconfetti/svelte": "^2.2.1",
    "@storybook/addon-essentials": "^8.4.6",
    "@storybook/addon-interactions": "^8.4.6",
    "@storybook/addon-svelte-csf": "^4.2.0",
    "@storybook/blocks": "^8.4.6",
    "@storybook/svelte": "^8.4.6",
    "@storybook/sveltekit": "^8.4.6",
    "@storybook/test": "^8.4.6",
    "@sveltejs/adapter-auto": "^3.3.1",
    "@sveltejs/kit": "^2.9.0",
    "@sveltejs/vite-plugin-svelte": "^5.0.1",
    "storybook": "^8.4.6",
    "svelte": "^5.2.12",
    "svelte-check": "^4.1.0",
    "typescript": "^5.7.2",
    "vite": "^6.0.1"
  }
```

Also tried with the alpha version but got the same error.  I created the project using svelte CLI `sv` that generates the following dependencies.

```json
{
    "@chromatic-com/storybook": "^3.2.2",
    "@storybook/addon-essentials": "^8.5.0-alpha.14",
    "@storybook/addon-interactions": "^8.5.0-alpha.14",
    "@storybook/addon-svelte-csf": "^5.0.0-next.13",
    "@storybook/blocks": "^8.5.0-alpha.14",
    "@storybook/svelte": "^8.5.0-alpha.14",
    "@storybook/sveltekit": "^8.5.0-alpha.14",
    "@storybook/test": "^8.5.0-alpha.14",
    "@sveltejs/adapter-auto": "^3.0.0",
    "@sveltejs/kit": "^2.0.0",
    "@sveltejs/vite-plugin-svelte": "^4.0.0",
    "eslint": "^9.7.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-storybook": "^0.11.1",
    "eslint-plugin-svelte": "^2.36.0",
    "globals": "^15.0.0",
    "mdsvex": "^0.11.2",
    "prettier": "^3.3.2",
    "prettier-plugin-svelte": "^3.2.6",
    "storybook": "^8.5.0-alpha.14",
    "svelte": "^5.0.0",
    "svelte-check": "^4.0.0",
    "typescript": "^5.0.0",
    "typescript-eslint": "^8.0.0",
    "vite": "^5.0.3"
  }
```

**Comment by yannbf** [comment]
@umaranis could you please provide a minimal reproduction so we can check it out? Thanks!

**Comment by umaranis** [comment]
For reproduction steps, I created a new svelte project using `sv` CLI. This time, it gives me different versions for dependencies. It is working fine with the following:

```json
{
"@chromatic-com/storybook": "^3.2.2",
"@eslint/compat": "^1.2.3",
"@playwright/test": "^1.45.3",
"@storybook/addon-essentials": "^8.4.7",
"@storybook/addon-interactions": "^8.4.7",
"@storybook/addon-svelte-csf": "^5.0.0-next.13",
"@storybook/blocks": "^8.4.7",
"@storybook/svelte": "^8.4.7",
"@storybook/sveltekit": "^8.4.7",
"@storybook/test": "^8.4.7",
"@sveltejs/adapter-auto": "^3.0.0",
"@sveltejs/kit": "^2.9.0",
"@sveltejs/vite-plugin-svelte": "^5.0.0",
"eslint": "^9.7.0",
"eslint-config-prettier": "^9.1.0",
"eslint-plugin-svelte": "^2.36.0",
"globals": "^15.0.0",
"mdsvex": "^0.11.2",
"prettier": "^3.3.2",
"prettier-plugin-svelte": "^3.2.6",
"storybook": "^8.4.7",
"svelte": "^5.0.0",
"svelte-check": "^4.0.0",
"typescript": "^5.0.0",
"typescript-eslint": "^8.0.0",
"vite": "^6.0.0",
"vitest": "^2.0.4"
}
```

**Comment by xeho91** [comment]
Following https://github.com/storybookjs/addon-svelte-csf/issues/238#issuecomment-2511196176

In the first case, this likely was the problem:

```diff
{
    "@chromatic-com/storybook": "^3.2.2",
    "@fontsource/fira-mono": "^5.1.0",
    "@neoconfetti/svelte": "^2.2.1",
    "@storybook/addon-essentials": "^8.4.6",
    "@storybook/addon-interactions": "^8.4.6",
-   "@storybook/addon-svelte-csf": "^4.2.0",
+   "@storybook/addon-svelte-csf": "^5.0.0-next.13",
    "@storybook/blocks": "^8.4.6",
    "@storybook/svelte": "^8.4.6",
    "@storybook/sveltekit": "^8.4.6",
    "@storybook/test": "^8.4.6",
    "@sveltejs/adapter-auto": "^3.3.1",
    "@sveltejs/kit": "^2.9.0",
    "@sveltejs/vite-plugin-svelte": "^5.0.1",
    "storybook": "^8.4.6",
    "svelte": "^5.2.12",
    "svelte-check": "^4.1.0",
    "typescript": "^5.7.2",
    "vite": "^6.0.1"
  }
```

In the second case, hard to tell, but those used versions have nothing to do with the subject of this issue:

```diff
{
    "@chromatic-com/storybook": "^3.2.2",
    "@storybook/addon-essentials": "^8.5.0-alpha.14",
    "@storybook/addon-interactions": "^8.5.0-alpha.14",
    "@storybook/addon-svelte-csf": "^5.0.0-next.13",
    "@storybook/blocks": "^8.5.0-alpha.14",
    "@storybook/svelte": "^8.5.0-alpha.14",
    "@storybook/sveltekit": "^8.5.0-alpha.14",
    "@storybook/test": "^8.5.0-alpha.14",
    "@sveltejs/adapter-auto": "^3.0.0",
    "@sveltejs/kit": "^2.0.0",
-   "@sveltejs/vite-plugin-svelte": "^4.0.0",
+   "@sveltejs/vite-plugin-svelte": "^5.0.0",
    "eslint": "^9.7.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-storybook": "^0.11.1",
    "eslint-plugin-svelte": "^2.36.0",
    "globals": "^15.0.0",
    "mdsvex": "^0.11.2",
    "prettier": "^3.3.2",
    "prettier-plugin-svelte": "^3.2.6",
    "storybook": "^8.5.0-alpha.14",
    "svelte": "^5.0.0",
    "svelte-check": "^4.0.0",
    "typescript": "^5.0.0",
    "typescript-eslint": "^8.0.0",
-   "vite": "^5.0.3"
+   "vite": "^6.0.0"
  }
```

I understand you had those version issues while generating the project template with `sv`. This addon doesn't have any control over it.

To sum up, it seems like the original issue is possibly resolved given the https://github.com/storybookjs/addon-svelte-csf/issues/238#issuecomment-2525428423.
