### ISSUE TITLE
add official way to mock `$page` in docs/test

### ISSUE THREAD

**Issue by wasdee** [storybookjs/addon-svelte-csf#249]
I've using a technique which is really hard to find in google. I think it would be niced to have this in `next` branch. 
- as docs in `README.md`
- as unit test

`https://tylergaw.com/blog/mocking-sveltekit-stores-in-storybook/`

```svelte
// MyComponent.stories.svelte
//...
<script>
  import { Story, Template } from '@storybook/addon-svelte-csf'
  // Note: we can only use Svelte context functions in scripts without context="module"
  import { setContext } from 'svelte'
  
  setContext('page-ctx', {
    data: {
      href: '/some/href/we/want',
      text: 'My Link Text'
    }
  })
</script>
//...
```

**Comment by xeho91** [comment]
`next` has branch focus on Svelte `v5`.

And mocking SvelteKit features is responsibility of other addon: [`@storybook/sveltekit`](https://storybook.js.org/docs/get-started/frameworks/sveltekit?renderer=svelte#api)

There's an API documentation: https://storybook.js.org/docs/get-started/frameworks/sveltekit?renderer=svelte#api

Is this what you're looking for?

**Comment by xeho91** [comment]
`next` has branch focus on Svelte `v5`.

And mocking SvelteKit features is responsibility of other addon: [`@storybook/sveltekit`](https://storybook.js.org/docs/get-started/frameworks/sveltekit?renderer=svelte#api)

There's an API documentation: https://storybook.js.org/docs/get-started/frameworks/sveltekit?renderer=svelte#api

Is this what you're looking for?

**Comment by wasdee** [comment]
oh ic. thank you for pointing out
