### ISSUE TITLE
Incompatibility with Svelte 5 projects b/c of peer dependency

### ISSUE THREAD

**Issue by ryanbmarx** [storybookjs/addon-svelte-csf#251]
### Describe the bug

This add-on's package.json lists `"svelte": "^4.0.0"` as a `peerDependency`, making it impossible for Svelte 5 projects to install without `npm i --force`. Svelte 5's legacy mode is compatible with Svelte 4.

### Steps to reproduce the behavior

1. Create a new Svelte 5 project of any kind.
2. `npm i -D addon-svelte-csf`

This will trigger an install peer dependency error.

### Expected behavior

Because there is compatibility with Svelte 5 projects, I expect the plugin to install smoothly, like any other package.

### Environment

 - OS: MacOS
 - Node.js version: 20.9.0
 - NPM version: 10.8.2
 - Browser (if applicable): n/a
 - Browser version (if applicable): n/a
 - Device (if applicable): n/a

### Additional context

The simplest fix, albeit a short-term one, would be to add Svelte 5 as the peer dependency:

```"svelte": "^4.0.0 || ^5.0.0"```

**Comment by JReinhold** [comment]
Svelte 5 support is still in prerelease, you can try it out by installing `@storybook/addon-svelte-csf@next`. Many users are already using it today, and we install the prerelease version by default when you init Storybook in a Svelte 5 project.
It's a big rewrite with a changed (and much better) API, so it will take some time before it's promoted to stable.

https://github.com/storybookjs/addon-svelte-csf/tree/next

**Comment by ryanbmarx** [comment]
Oh, that's wonderful. Thank you for letting me know. 

Our use is internal only, so seems like the pre-release will fit the bill.
