### ISSUE TITLE
[Bug]  Function called outside component initialization error 

### ISSUE THREAD

**Issue by ritchieanesco** [storybookjs/addon-svelte-csf#26]
### Describe the bug

Latest version of **Storybook with experimental Webpack 5** throws error:
> Error extracting stories Error: Function called outside component initialization Error: Function called outside component initialization

for each of the "demo" stories that uses `@storybook/addon-svelte-csf`. Stories that use argtypes works as expected.
 
### Steps to reproduce the behavior

1. Type `npm run storybook` (start-storybook -p 6006)
2. Go to preferred browser and load http://localhost:6006/
3. See error

### Expected behavior

Stories to load and render on page.

### Screenshots and/or logs

<img width="1069" alt="Screen Shot 2021-05-18 at 11 27 31 pm" src="https://user-images.githubusercontent.com/1123992/118659662-dcf64480-b830-11eb-8a1f-32e9813e1b6d.png">

### Environment

 - OS: MAC OS 11.3.1
 - Node.js version: 14.4.0
 - NPM version: 6.14.5
 - @storybook/addon-actions: 6.3.0-alpha.31
 - @storybook/addon-essentials: 6.3.0-alpha.31
 - @storybook/addon-links: 6.3.0-alpha.31
 - @storybook/addon-svelte-csf: 1.0.0
 - @storybook/builder-webpack5: 6.3.0-alpha.31
 - @storybook/svelte:  6.3.0-alpha.31

### Additional context

**storybook webpack**
```js
module.exports = {
  stories: [
    `../../src/**/*.stories.mdx`,
    `../../src/**/*.stories.@(ts|svelte)`,
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-svelte-csf",
  ],
  core: {
    builder: "webpack5",
  },
  svelteOptions: {
    preprocess: require("svelte-preprocess")({
      babel: {
        plugins: ["@vanilla-extract/babel-plugin"],
      },
    }),
  },
  webpackFinal: (config) => {
    config.module.rules.push({
      test: /\.(js|ts)$/,
      exclude: /node_modules/,
      use: {
        loader: "babel-loader",
        options: {
          plugins: [
            "@babel/plugin-proposal-optional-chaining",
            "@babel/plugin-transform-modules-commonjs",
            "@babel/plugin-proposal-nullish-coalescing-operator",
          ],
        },
      },
    })
    config.module.rules.push({
      test: /\.(css.ts)$/,
      exclude: /node_modules/,
      use: {
        loader: "babel-loader",
        options: {
          plugins: ["@vanilla-extract/babel-plugin"],
        },
      },
    })
    config.module.rules.push({
      test: /\.ts?$/,
      use: [{ loader: "ts-loader", options: { transpileOnly: true } }],
    })
    config.plugins.push(new MiniCssExtractPlugin())
    config.plugins.push(new VanillaExtractPlugin())

    config.resolve.fallback = {
      http: false,
      crypto: false,
      path: false,
    }
    return config
  },
}
```

**Comment by j3rem1e** [comment]
You have two copies of the svelte runtime in your application. You should use an alias rules in your webpage config, as seen in the official svelte-loader doc.

**Comment by ritchieanesco** [comment]
Ah yes! That fixed it. Thanks @j3rem1e !
