### ISSUE TITLE
Publish ESM

### ISSUE THREAD

**Issue by shilman** [storybookjs/addon-svelte-csf#29]
### Describe the bug

Webpack dependency for this package is causing problems for Vite users here https://github.com/eirslett/storybook-builder-vite/issues/16#issuecomment-855219901

Meanwhile @winkerVSbecks has added ESM support to `addon-kit` here: https://github.com/storybookjs/addon-kit/pull/11

If we could get those changes into this package & republish, that might help the Vite users move forward cc @TheComputerM

@j3rem1e WDYT?

**Comment by TheComputerM** [comment]
Can I try to add ESM support? will you merge it?

**Comment by TheComputerM** [comment]
@shilman https://github.com/storybookjs/addon-svelte-csf/pull/30

**Comment by shilman** [comment]
Merged & published as 1.1.0
