### ISSUE TITLE
Type definitions missing from release

### ISSUE THREAD

**Issue by mgood** [storybookjs/addon-svelte-csf#31]
Thanks for merging #20 to add TypeScript definitions, but it looks like the file is not included in the released package for `v1.0.1`.

I'm adding TypeScript support to an existing project, and saw that you had just released 1.0.1 with types, but after upgrading it in my project the `.d.ts` file is still missing. 

Based on `node_modules/@storybook/addon-svelte-csf/CHANGELOG.md` I can see that it contains the release notes for `1.0.1`, but `index.d.ts` is not present.

So, it seems like there's a setting missing in `package.json` to include that file when packaging it for release.

**Comment by shilman** [comment]
Fixed in 1.1.0 I believe. Closing!
