### ISSUE TITLE
Svelte native stories not working with Webpack 5 [Bug]

### ISSUE THREAD

**Issue by ryu-man** [storybookjs/addon-svelte-csf#32]
### Describe the bug

Stories written in Svelte native format will not be loaded when using Webpack 5 as the default builder.

### Steps to reproduce the behavior

1.  Run npx sb init --builder webpack5
2. Choose svelte as the type
3. Run `npm run storybook` 
4. You will notice stories  written in a .svelte files  are not detected

### Expected behavior

Stories written in .svelte files should be detected when using Webpack 5 

### Environment

 - OS: [Windows 10]
 - Node.js version: [14.17.0]
 - NPM version: [6.14.13]

**Comment by j3rem1e** [comment]
Do you have an error in your browser console ?

**Comment by ryu-man** [comment]
![Screenshot 2021-06-12 150426](https://user-images.githubusercontent.com/25468773/121778629-a1306f80-cb8f-11eb-8229-c3beac969449.png)

this is a screenshot of the console

**Comment by j3rem1e** [comment]
See #26

**Comment by ryu-man** [comment]
Thanks @j3rem1e , I add a resolve configuration for Webpack and that fixed the problem,
I will share my .storybook/main.js those who could face this issue in the future

```
const path = require("path");

module.exports = {
	stories: [
		"../stories/**/*.stories.mdx",
		"../stories/**/*.stories.@(js|jsx|ts|tsx|svelte)",
	],
	addons: [
		"@storybook/addon-links",
		"@storybook/addon-essentials",
		"@storybook/addon-svelte-csf",
	],
	core: {
		builder: "webpack5",
	},

	webpackFinal: async (config, { configType }) => {
		// `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
		// You can change the configuration based on that.
		// 'PRODUCTION' is used when building the static version of storybook.

		config.resolve = {
			...config.resolve,
			// see below for an explanation
			alias: {
				svelte: path.resolve("node_modules", "svelte"),
			},
			extensions: [".mjs", ".js", ".svelte"],
			mainFields: ["svelte", "browser", "module", "main"],
		};

		// Return the altered config
		return config;
	},
};

```
