### ISSUE TITLE
[Bug] Code section only shows template

### ISSUE THREAD

**Issue by MarvinJWendt** [storybookjs/addon-svelte-csf#39]
Hi, the `Show code` button in the docs section only shows the Template.

![image](https://user-images.githubusercontent.com/31022056/149207084-403fed77-e02d-43df-beac-5c207ec8461f.png)

I would expect to see the actual attributes there (from the configuration below). Are there any plans to implement this?

**Comment by Tlahey** [comment]
Same for me, but with `storybook/svelte@6.3.7` I don't have any issues

**Comment by j3rem1e** [comment]
Related to https://github.com/storybookjs/storybook/issues/17560
