### ISSUE TITLE
White Screen of Death v1.1.0 ⬜️  ☠️ 

### ISSUE THREAD

**Issue by codingwithchris** [storybookjs/addon-svelte-csf#45]
### Describe the bug
My storybook is building properly for dev with no errors and is building for production with no errors, but when I open up the local URL, I am getting a white screen with a ton of console errors.

As far as I can tell, this is basically the same error as seen here:
[https://github.com/storybookjs/storybook/issues/14410](https://github.com/storybookjs/storybook/issues/14410)

### Steps to reproduce the behavior

1. Remove all svelte stories
2. run `start-storybook -p 6006 --no-manager-cache`
3. Observe that there are no errors in the console
4. Visit `localhost:6006`
5. See that the storybook UI is rendering & working but not finding any stories (as expected)
6. Add a single svelte story that only renders the simple text: `Hello World`.
7. Restart Storybook
8. Visit `localhost:6006`
9. See storybook white screen of death with tons of console errors (linked below)
10. Test any number of Svelte components and see that any svelte story causes the white screen of death
11. Remove all svelte stories and see that storybook is working again.

### Expected behavior
I expect to see my stories rendered and not have the entire Storybook UI crash

### Screenshots and/or logs

![Screen Shot 2022-04-05 at 9 12 25 AM](https://user-images.githubusercontent.com/17693193/161761612-31e9bb4e-0281-4a05-97d0-692b087cb010.png)

![Screen Shot 2022-04-04 at 4 45 00 PM](https://user-images.githubusercontent.com/17693193/161759480-1f7cbc9d-4c9e-4c4d-81b9-b31da832e6e7.png)

![Screen Shot 2022-04-04 at 4 45 05 PM](https://user-images.githubusercontent.com/17693193/161759492-6f380b55-36e8-4923-b550-13ae083cbb2d.png)

### Environment
 - OS: macOS Monterey 12.2
 - Node.js version: 16.13.1
 - Yarn version: 1.22.18
 - Browser (if applicable): chrome
 - Browser version (if applicable): Version 100.0.4896.60 (Official Build) (arm64)
 - Device (if applicable): M1 MacBook pro

### Additional context
**Relevant Versions**
```
"@storybook/addon-actions": "^6.4.20",
"@storybook/addon-essentials": "^6.4.20",
"@storybook/addon-links": "^6.4.20",
"@storybook/addon-svelte-csf": "^1.1.0",
"@storybook/svelte": "^6.4.20",
"svelte": "^3.46.4",
"svelte-loader": "^3.1.2",
"svelte-preprocess": "^4.10.4",
```

Also I should note that running `build-storybook` also results in a clean build but white screens upon start.

**Comment by j3rem1e** [comment]
Probably fixed by #42 , there is conflicts in some dependencies.

**Comment by j3rem1e** [comment]
Can you test with v2.0.1 ?

**Comment by codingwithchris** [comment]
Still seems to be broken for me :/

**Comment by j3rem1e** [comment]
do you have a repro for this issue ?

**Comment by codingwithchris** [comment]
Unfortunately, my repo is private as it's a work project... I can try and spin up a barebones test repo but not sure I have time this week. FWIW... I'm getting errors with both Webpack 4, Webpack 5, and the Vite builder with addon-svelte-csf at `2.0.1`.

**Comment by j3rem1e** [comment]
https://github.com/storybookjs/storybook/issues/17161

**Comment by j3rem1e** [comment]
Closing this issue because it's not related to this addon
