### ISSUE TITLE
How do I use argTypes including controls?

### ISSUE THREAD

**Issue by ericmand** [storybookjs/addon-svelte-csf#5]
Are they provided as attributes to Meta? How are they formatted? Forgive me if there was an example somewhere, I didn't see it. Also forgive me if this shouldn't be asked in an issue. Not sure where to ask it.

**Comment by betaboon** [comment]
@ericmand if i understand you correctly you're looking for this: https://github.com/storybookjs/addon-svelte-csf/pull/1#issuecomment-788099560

**Comment by ericmand** [comment]
Sure does. Thank you!
