### ISSUE TITLE
How to import stories into stories and reuse arguments?

### ISSUE THREAD

**Issue by zenoli** [storybookjs/addon-svelte-csf#51]
In the [official svelte storybook tutorial](https://storybook.js.org/tutorials/intro-to-storybook/svelte/en/composite-component/), they use a pattern where stories get imported into other stories, in order to reuse the arguments defined in the imported stories:

`import * as TaskStories from './Task.stories';`

and then, `TaskStories` arguments can be reused as `TaskStories.Default.args`.

Is this possible using this addon?

**Comment by j3rem1e** [comment]
This part of the documentation is more axed to React and can't be translated with svelte native format.

What you can do is probably export common parameters from an external js file and reuse them.
