### ISSUE TITLE
[Bug] Special characters cause error in Storybook

### ISSUE THREAD

**Issue by brandonmcconnell** [storybookjs/addon-svelte-csf#54]
### Describe the bug

When I add special characters to the name of a Story, for example: `<Story name="Horizontal (Default)" args={{}} />`, the `(` and `)` symbols appear to break stories, and they can no longer be found.

### Expected behavior

I would expect to be able to include any special characters in Story names and have them rendered appropriately.

**Comment by shilman** [comment]
:rocket: Issue was released in [`v2.0.2`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v2.0.2) :rocket:

**Comment by shilman** [comment]
:rocket: Issue was released in [`v2.0.2`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v2.0.2) :rocket:

**Comment by shilman** [comment]
:rocket: Issue was released in [`v2.0.2`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v2.0.2) :rocket:
