### ISSUE TITLE
Add indexer support

### ISSUE THREAD

**Issue by shilman** [storybookjs/addon-svelte-csf#65]
Currently `stories.svelte` files are incompatible with:
- story index generation https://github.com/storybookjs/storybook/issues/18081
- storybook test runner https://github.com/storybookjs/test-runner/issues/80

To address this, we've added an "indexer" API to Storybook core for 7.0: https://github.com/storybookjs/storybook/pull/18355

If `addon-svelte-csf` were to implement an indexer, it would solve the above problems, plus other future problems as we build more on top of the story index (which we will definitely do more of in core)

**Comment by j3rem1e** [comment]
I have a working implementation in a private branch. I have to add tests and check how I can merge this without loosing compatibility with v6

**Comment by shilman** [comment]
@j3rem1e that's wonderful news! It might make sense to release that change in an alpha rather than a full release. The indexer API is 7.0-alpha and might change between now and the final release. Specifically, we might update it to make watch mode possible in the test runner. cc @yannbf

**Comment by shilman** [comment]
:rocket: Issue was released in [`v2.0.9`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v2.0.9) :rocket:
