### ISSUE TITLE
The requested module does not provide an export named 'useContext'

### ISSUE THREAD

**Issue by anderfernandes** [storybookjs/addon-svelte-csf#67]
### Describe the bug

After running `npm update` in my SvelteKit/Storybook project, stories don't load anymore. I've also tried with a fresh SvelteKit/Storybook project, the same happens.

### Steps to reproduce the behavior

1. Set up a new SvelteKit/Storybook project
2. `npm run storybook`
3. Go to Storybook URL
4. Stories don't load

### Expected behavior

Stories to load.

### Screenshots and/or logs
![Screenshot_20220811_220719](https://user-images.githubusercontent.com/4932608/184278064-bf863b62-d452-4e81-bc2a-95aeb94a3478.png)

### Environment

 - OS: Arch Linux
 - Node.js version: 16.16.0
 - NPM version: 8.17.0
 - Browser (if applicable): Chromium
 - Browser version (if applicable): 104.0.5112.79
 - Device (if applicable): Dell XPS 15 9560

### Additional context

When downgrading `vite` to 3.0.5, things work as expected.

**Comment by carusog** [comment]
@anderfernandes yesterday I set up a fresh install to test the bug of native svelte stories, written in TS. It works for me (of course, when not using TS and using relative imports).
You can find it here: #4 (last comment).

**Comment by anderfernandes** [comment]
@carusog I believe this was a problem with vite. In their 3.0.7 release there was something that was breaing cjs imports in monorepos. I will test it when I get home tonight.

**Comment by WilHall** [comment]
Same issue here - `@storybook/addon-svelte-csf@2.0.7` and `vite@3.0.7` cause this issue for us, but downgrading to `vite@3.0.5` fixes it.

**Comment by snorreks** [comment]
I got it working on vite@3.0.9 :thumbsup:

**Comment by anderfernandes** [comment]
It works in vite@3.0.9. Hooray!!!
