### ISSUE TITLE
[Feature]: Typescript - Add typings to both <Template> and <Story> args

### ISSUE THREAD

**Issue by AcePetrucci** [storybookjs/addon-svelte-csf#68]
### Describe the bug

Whenever I use both the `<Template>` and `<Story>` components, it would be great to be able to set the expected type of `let:args`.

Ex:
```js
<script lang="ts">
  import Choice from './Choice.svelte';
  import choiceProps from './choiceProps.ts';
</script>

<Template let:args id="ChoiceTemplate">
  // Ideally I would have the option to set that args has the choiceProps type
  <Choice {...args} />
</Template>

<Story
  id="ChoiceStory"
  name="Choice"
  template="ChoiceTemplate"
  args={{
    choiceText: 'Choice 1',
    value: 'choice-1',
    name: 'choice-1'
  }} // Same thing here
/>
```

**Comment by Masstronaut** [comment]
I'm not sure this is solveable within svelte-csf; svelte doesn't have support for typescript outside of the `script` tags, which has been an open issue for several years. See the issue at [@sveltejs/svelte #4701](https://github.com/sveltejs/svelte/issues/4701)

**Comment by benmccann** [comment]
I'm not sure what this is really requesting to change in `addon-svelte-csf` as it seems like something that would need to be addressed in Svelte itself as @Masstronaut suggested. His suggestion seems like a reasonable one in the meantime. Given that, I'm going to close this in favor of https://github.com/sveltejs/svelte/issues/4701

**Comment by Masstronaut** [comment]
@benmccann in case it's not on your roadmap, svelte 5 adds typescript support in the svelte markup [sveltejs/svelte#9482](https://github.com/sveltejs/svelte/pull/9482), so I believe this should be possible now (and greatly appreciated! 🙏)

Not sure if it makes more sense to re-open here or spin up a new issue for it. It would require svelte 5, making it a potentially breaking change for svelte 4 users.
