### ISSUE TITLE
[Bug] 'target' is a required option

### ISSUE THREAD

**Issue by gbkwiatt** [storybookjs/addon-svelte-csf#75]
I am using `2.0.8--canary.8172dc5.0` version so it works with storybook 7 alpha, (indexer). 
All of the sudden after updating to latest storybook alpha version (42), I get errors on all component `'target' is a required option`
I can see that it's only triggered on dev, but haven't seen that before - what does it mean ?

**Comment by JReinhold** [comment]
Closing as duplicate of https://github.com/storybookjs/storybook/issues/19634
