### ISSUE TITLE
[Bug] Show code doesn't work properly in MDX for stories that use Template

### ISSUE THREAD

**Issue by idosius** [storybookjs/addon-svelte-csf#78]
### Describe the bug

When using Svelte component stories that use `Template` in an MDX, then viewing that page in Storybook and clicking "Show code", the code isn't shown properly.

### Steps to reproduce the behavior

1. Create a Svelte story using `viewMode: 'docs'` that loads an MDX page and uses `Template` (see example below)
2. Execute `npm run storybook`
3. Open the above page in Storybook
4. Click "Show code" for the component
5. The source code will be displayed incorrectly, e.g. `<Proxy<RenderContext> primary/>`

Note: when using Svelte components directly in a Story without Template, "Show code" works just fine

### Expected behavior

The correct code should be displayed according to the Template and args, e.g. `<Button primary label="Button" />`

### Screenshots and/or logs

![Opera Snapshot_2022-11-11_165001_localhost](https://user-images.githubusercontent.com/809766/201376368-800e3e2c-3d9c-4949-a57c-a488708db24f.png)

### Environment

 - OS: macOS Ventura 13.0
 - Node.js version: 16.15.1
 - NPM version: 8.11.0
 - Browser (if applicable): Opera
 - Browser version (if applicable): 92.0
 - Device (if applicable): MacBook Pro

### Additional context

Example Button.stories.svelte:

```
<script>
  import { Meta, Story, Template } from '@storybook/addon-svelte-csf'

  import Button from './Button.svelte'
  import page from './Button.mdx'
</script>

<Meta
  title="Example/Button"
  component={Button}
  parameters={{
    docs: { page },
    viewMode: 'docs',
  }}
/>

<Template let:args>
  <Button {...args} label="Button" />
</Template>

<Story name="Primary" args={{ primary: true }} />
```

Example Button.mdx:
```
import { Story, Canvas } from '@storybook/addon-docs'

# Button

## Variants

### Primary

<Canvas>
  <Story id="example-button--primary" />
</Canvas>
```

Button.svelte (default one that arrives with Storybook for Svelte):
```
<script>
  import './button.css'
  import { createEventDispatcher } from 'svelte'
  /**
   * Is this the principal call to action on the page?
   */
  export let primary = false

  /**
   * What background color to use
   */
  export let backgroundColor
  /**
   * How large should the button be?
   */
  export let size = 'medium'
  /**
   * Button contents
   */
  export let label = ''

  let mode = primary
    ? 'storybook-button--primary'
    : 'storybook-button--secondary'

  let style = backgroundColor ? `background-color: ${backgroundColor}` : ''

  const dispatch = createEventDispatcher()

  /**
   * Optional click handler
   */
  function onClick(event) {
    dispatch('click', event)
  }
</script>

<button
  type="button"
  class={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
  {style}
  on:click={onClick}
>
  {label}
</button>
```

**Comment by idosius** [comment]
Maybe this has to do with using Vite as the builder? When using Webpack this issue doesn't reproduce

main.cjs that reproduces the issue:
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx|svelte)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    '@storybook/addon-svelte-csf',
  ],
  "framework": "@storybook/svelte",
  "core": {
    "builder": "@storybook/builder-vite",
    disableTelemetry: true
  },
  "svelteOptions": import('../svelte.config.js'),
  "features": {
    // set to false to support Svelte stories
    // reference: https://github.com/storybookjs/storybook/issues/16673#issuecomment-1133477439
    storyStoreV7: false,
  }
}
```

**Comment by j3rem1e** [comment]
`Proxy` is the name of the component created by `svelte-hmr`, and `RenderContext` is the root of the hierarchy of the component written with this addon.

I have sent a PR in Storybook to fix issues with hmr, but I don't know if it will fix this issue.

**Comment by j3rem1e** [comment]
This seem to be fixed. At least I cannot reproduce it with the latest version of this addon and storybook. 

@idosius don't hesite to reopen if you have any problem.
