### ISSUE TITLE
[Bug]: Identifier 'parser' has already been declared on stories using `.svelte` extension

### ISSUE THREAD

**Issue by jnschrag** [storybookjs/addon-svelte-csf#83]
### Describe the bug

When using Sveltekit with version 7.0.0-beta version (have gotten this error on betas v3-7) with the `addon-svelte-csf` version `3.0.0-next.1`, I get this error when trying to view a component that use the Svelte template syntax (eg. [`Button.stories.svelte`](https://github.com/jnschrag/storybook-sveltekit-test/blob/main/src/lib/components/Button/Button.stories.svelte)).

```
Identifier 'parser' has already been declared
```

This does not occur in components that don't use `.svelte` syntax.

### Steps to reproduce the behavior

[Here](https://github.com/jnschrag/storybook-sveltekit-test) is a test repo that has a library skeleton of Sveltekit installed and a fresh Storybook install.

### Expected behavior

I'd expect to be able to use `.stories.svelte` for a stories file.

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/1896496/207644430-d44bfcca-d4ba-4bf9-972f-e8bad0e58549.png)
What I see when I try to access the Button component. The `Header` & `Page` components load just fine.

![image](https://user-images.githubusercontent.com/1896496/207644117-513ad665-90e8-413b-903e-5ec506ab6084.png)

Is what I see in the console.

### Environment

 - OS: MacOS 11.7
 - Node.js version: v16.15.1
 - NPM version: 8.11.0
 - Browser (if applicable): All

### Additional context

I know that both the version of Storybook & the svelte-addon are in beta/being actively developed, so this might just be an issue that hasn't been resolved yet. But I didn't see any bugs related to this and wanted to report just in case others have this problem.

**Comment by R12-cookies** [comment]
Having the same issue here
