### ISSUE TITLE
[Bug] Show Code doesn't work when using Svelte-native format and <Template/> tags

### ISSUE THREAD

**Issue by kyleshepherd** [storybookjs/addon-svelte-csf#86]
### Describe the bug

If you use a Svelte-native format for a story, and use the `<Template/>` tags along with args to reduce boilerplate, the Show Code option on the docs page doesn't display the actual code for the component.

Example:
```
// Container.stories.svelte
<script lang="ts">
  import { Meta, Template, Story } from "@storybook/addon-svelte-csf";
  import Container from "./Container.svelte";
</script>

<style lang="scss">
  .block {
    background-color: $dark;
    height: 100vh;
    width: 100%;
  }
</style>

<Meta title="Components/Container" component={Container} />

<Template let:args>
  <Container {...args}>
    <div class="block" />
  </Container>
</Template>

<Story name="Default" />
```

Results in this:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/25406287/208672496-8180dc9f-86a9-48f5-a277-6f51ff12e3c3.png">

### Steps to reproduce the behavior

1. Create a Svelte-native story using Template tags (and using Vite Builder, maybe this is the issue)
2. View Story Docs
3. Click "Show Code"

### Expected behavior

Viewing the code should display the component code the same way it does when not using Templates such as 
```
<Story name="Default">
    <Container>
        <div class="block"/>
    </Container>
</Story>
```

### Environment

 - OS: MacOS 13.1
 - Node.js version: v16.17.0
 - NPM version: 8.15.0

**Comment by kyleshepherd** [comment]
bumping this after the holiday break :)

**Comment by kyleshepherd** [comment]
is there anyone maintaining this repo?

on top of the mentioned issue, you can't create your own DocsPage (or even hide the default one) for some reason

The following doesn't work:

```
<Meta
  title="Components/SpriteIcon"
  component={SpriteIcon}
  argTypes={{
    icon: { control: "text" },
    iconPath: { control: "text" },
    width: { control: "number" },
    height: { control: "number" },
    color: { control: "color" },
  }}
  parameters={{
    docs: {
      page: null
    },
  }}
/>
```

**Comment by MilesWellsSVT** [comment]
I had the same bug crop up when upgrading from Storybook 6 to 7 while also swapping over from Webpack to Vite. Switching back to Webpack while still on Storybook 7 I get the expected code format:
![image](https://user-images.githubusercontent.com/80766315/234410401-c5e9a528-5b32-4f16-a552-5da48e223b08.png)

However, when spreading args for controls like so:
```
<Story let:args>
	<Alert {...args}>Alert</Alert>
</Story>
```
I get this behavior for events (the Alert component here dispatches a "hide" event via the `createEventDispatcher`):
![image](https://user-images.githubusercontent.com/80766315/234410685-18935b9c-aab5-436e-a489-7493a2d6a96c.png)

I don't know if this is related, but I did not see this behavior when on SB 6 with version `2.0.10` of this plugin. Now I'm on SB 7 and plugin version `3.0.2`.

**Comment by crisward** [comment]
Also using svelte on 7. If I setup the story with no args, I get the correct code block

```html
<Story name="Primary Extra Small">
  <Button mode="primary" size="xs">Button</Button>
</Story>
```

<img width="1023" alt="Screenshot 2023-06-21 at 09 02 05" src="https://github.com/storybookjs/addon-svelte-csf/assets/3109157/cafcdd02-a432-46cc-925c-c493f92e5500">

However with args or template block, I get

<img width="1018" alt="Screenshot 2023-06-21 at 09 02 45" src="https://github.com/storybookjs/addon-svelte-csf/assets/3109157/af5dc6a8-c041-4d23-aa27-72b65f5c5960">

npm ls (if it helps)

```
├── @babel/preset-env@7.22.5
├── @rollup/plugin-alias@3.1.2
├── @rollup/plugin-commonjs@17.1.0
├── @rollup/plugin-node-resolve@11.2.1
├── @storybook/addon-essentials@7.0.22
├── @storybook/addon-interactions@7.0.22
├── @storybook/addon-links@7.0.22
├── @storybook/addon-svelte-csf@3.0.3
├── @storybook/blocks@7.0.22
├── @storybook/svelte-vite@7.0.22
├── @storybook/svelte@7.0.22
├── @storybook/testing-library@0.0.14-next.2
├── @sveltejs/svelte-repl@0.4.1
├── @sveltejs/vite-plugin-svelte@2.4.1
├── @testing-library/svelte@3.0.3
├── @web/test-runner@0.14.0
├── chai@4.3.4
├── chart.js@2.9.4
├── core-js@3.10.0
├── fetch-mock@9.11.0
├── msw-storybook-addon@1.8.0
├── page.js@4.13.3
├── react-dom@18.2.0
├── react@18.2.0
├── rollup-plugin-css-only@3.1.0
├── rollup-plugin-livereload@2.0.5
├── rollup-plugin-svelte@7.1.0
├── rollup-plugin-terser@7.0.2
├── rollup@2.79.1
├── showdown@1.9.1
├── smoothscroll-polyfill@0.4.4
├── storybook@7.0.22
├── svelte@3.59.1
├── vite@4.3.9
├── whatwg-fetch@3.6.2
└── xss@1.0.8
```

**Comment by j3rem1e** [comment]
Closing this issue because the generation of Svelte snippets are not done by this addon but is the responsibility of the core Storybook/svelte and there is already issues about this bug.

**Comment by giamir** [comment]
@j3rem1e Since this issue is now closed could you link here which issue in Storybook/svelte we should follow? Thank you.

**Comment by j3rem1e** [comment]
At least this one : https://github.com/storybookjs/storybook/issues/24008
