### ISSUE TITLE
[Bug] Can't set tags on <Meta> component to enable fine-grained autodocs

### ISSUE THREAD

**Issue by hallefsantos** [storybookjs/addon-svelte-csf#87]
Hey guys, is there a way to use `tags: ['autodocs']` to auto-generate documentation? Or is there a better way? 

I've tried this, but didn't work.

![image](https://user-images.githubusercontent.com/20205767/210617049-837fdeb9-775e-44bb-a7c0-ec2592ac7d64.png)

### Environment

System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.14 GB / 7.74 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  npmPackages:
    vite: 4.0.0 => 4.0.0

**Comment by JReinhold** [comment]
It should work the way you tried, but I'm not surprised that it doesn't, since this is a new prop to the top level meta definition.
Thanks for bringing this up!

In the mean time, the best workaround currently is to set autodocs globally, but that won't allow you specify it at the file level unfortunately.

https://storybook.js.org/docs/7.0/svelte/writing-docs/docs-page#configure

```js
// .storybook/main.js

module.exports = {
  ...
  docs: {
    ...
    autodocs: true,
  },
};
```

**Comment by JReinhold** [comment]
@hallefsantos did it work natively as you expected? if not, then let's keep this open as a bug report to fix it.

**Comment by enyo** [comment]
@JReinhold  just ran into this and can confirm that setting auto docs on the Meta component does _not_ work.

**Comment by viktorgullmark** [comment]
@JReinhold Same here, cant set tags on Meta

**Comment by Masstronaut** [comment]
@JReinhold the workaround of setting autodocs globally worked for my use case. I do still think it's worth adding the missing fields to the `Meta` component though.

**Comment by j3rem1e** [comment]
See #134
