### ISSUE TITLE
[Bug] typescript not working in stories for svelte

### ISSUE THREAD

**Issue by mantismamita** [storybookjs/addon-svelte-csf#88]
### Steps to reproduce the behavior

Reproducable in https://github.com/mantismamita/storybook-svelte-bugreproduction/tree/typescript-in-story

1. npm install
2. npm run storybook

I see 
```
WARN 🚨 Extraction error on src/stories/Visual.stories.svelte: Unexpected token (2:14)
WARN 1: <script lang="ts">
WARN 2:   import type { Visual as VisualType } from 'visual';
WARN                  ^
WARN 3: 
WARN 4:   import { Meta, Story, Template } from '@storybook/addon-svelte-csf';
```

### Expected behavior

I expect storybook to load 

### Screenshots and/or logs

```
@storybook/cli v7.0.0-beta.21

info => Starting manager..
info => Serving static files from ././static at /
WARN 🚨 Extraction error on src/stories/Visual.stories.svelte: Unexpected token (2:14)
WARN 1: <script lang="ts">
WARN 2:   import type { Visual as VisualType } from 'visual';
WARN                  ^
WARN 3: 
WARN 4:   import { Meta, Story, Template } from '@storybook/addon-svelte-csf';
CompileError [ParseError]: Unexpected token
    at error (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/svelte/compiler.js:13771:20)
    at Parser$1.error (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/svelte/compiler.js:13847:7)
    at Parser$1.acorn_error (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/svelte/compiler.js:13841:12)
    at Object.read_script [as read] (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/svelte/compiler.js:7372:14)
    at tag (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/svelte/compiler.js:12891:31)
    at new Parser$1 (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/svelte/compiler.js:13807:17)
    at parse$I (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/svelte/compiler.js:13934:20)
    at Object.compile (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/svelte/compiler.js:40767:17)
    at null.extractStories (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/@storybook/addon-svelte-csf/dist/cjs/parser/extract-stories.js:35:14)
    at Object.svelteIndexer (/Users/kirstencassidy/Work/storybook-svelte-bugreproduction/node_modules/@storybook/addon-svelte-csf/dist/cjs/preset/indexer.js:7:16) {
  code: 'parse-error',
  start: { line: 2, column: 14, character: 33 },
  end: { line: 2, column: 14, character: 33 },
  pos: 33,
  filename: undefined,
  frame: '1: <script lang="ts">\n' +
    "2:   import type { Visual as VisualType } from 'visual';\n" +
    '                 ^\n' +
    '3: \n' +
    "4:   import { Meta, Story, Template } from '@storybook/addon-svelte-csf';"
}
```

### Environment

```
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    @storybook/addon-a11y: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-actions: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-essentials: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-interactions: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-links: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-postcss: ^3.0.0-alpha.1 => 3.0.0-alpha.1 
    @storybook/addon-svelte-csf: ^3.0.0-next.3 => 3.0.0-next.3 
    @storybook/builder-vite: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/client-logger: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/svelte: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/sveltekit: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
### Additional context
```

Typescript is compiling correctly in the components themselves.

**Comment by theosenoussaoui** [comment]
Would love to see this as well. Same thing in happening here and is currently blocking us from having a running Storybook (can't install a prior version to 7 due to the latest `vite` dependencies of SvelteKit).

**Comment by theosenoussaoui** [comment]
> > (can't install a prior version to 7 due to the latest `vite` dependencies of SvelteKit).
> 
> There's a workaround. If you lock the dependency `@sveltejs/vite-plugin-svelte` to `1.4.0` (latest before the major version 2) it allows you to use latest version of svelte and svelte kit with storybook@6

Hey, thanks for the tip !

Do you mean modify the `package.json` locally in my `node_modules` folder ? I could do it but since this is not a personal project I'm not sure I should do it, but will definitely try this tomorrow and report.

**Comment by BeeMargarida** [comment]
> > > (can't install a prior version to 7 due to the latest `vite` dependencies of SvelteKit).
> > 
> > 
> > There's a workaround. If you lock the dependency `@sveltejs/vite-plugin-svelte` to `1.4.0` (latest before the major version 2) it allows you to use latest version of svelte and svelte kit with storybook@6
> 
> Hey, thanks for the tip !
> 
> Do you mean modify the `package.json` locally in my `node_modules` folder ? I could do it but since this is not a personal project I'm not sure I should, but will definitely try this tomorrow and report.

Add it as dependency of your project. `@sveltejs/vite-plugin-svelte` is a dependency of SK, if I'm not mistaken. SK1 uses version 2, but if you add it as a dependency in your repo and force it to 1.4, it will use that one.

**Comment by theosenoussaoui** [comment]
Thanks @BeeMargarida it's working as a temporary workaround (but I'm not sure I'd like to know how you found it) for now. 🎉 
 Might have some things to verify for my Svelte application though.

Still would love to see some Typescript support for this addon and the next release of Storybook.

**Comment by theosenoussaoui** [comment]
@JReinhold @shilman the problem still remains, thank you guys for acknowledging this, have a good day.

**Comment by mantismamita** [comment]
This is actually blocking all of our updates at the moment. Strong types are one of the reasons we wanted to update https://storybook.js.org/blog/improved-type-safety-in-storybook-7/

**Comment by JReinhold** [comment]
The reason this is happening is because the new indexer doesn't do any preprocessing before compiling and extracting the stories from the stories file. And for some reason the indexer sidesteps Vite/Webpack and reads the file content raw, so the preprocessing done in the builders is also not happening.

Either we need to:
1. Not sidestep the builders. I suspect this is happening because [we're using `fs.readFile` instead of `import`](https://github.com/storybookjs/addon-svelte-csf/blob/next/src/preset/indexer.js#L5)
2. Load and apply the preprocesser before trying to extract stories, similar to [how eg. the Vite plugin does it currently](https://github.com/storybookjs/addon-svelte-csf/blob/next/src/plugins/vite-svelte-csf.js#L22-L26).

**Comment by mantismamita** [comment]
> 2. Load and apply the preprocesser before trying to extract stories, similar to [how eg. the Vite plugin does it currently](https://github.com/storybookjs/addon-svelte-csf/blob/next/src/plugins/vite-svelte-csf.js#L22-L26). The tricky thing here is to do it in a builder agnostic way, that doesn't introduce a specific builder-dependency.

The advantage here would be that other options in `svelteOptions.preprocess` would theoretically be applied.

**Comment by JReinhold** [comment]
Fixed in https://github.com/storybookjs/addon-svelte-csf/releases/tag/v3.0.0-next.4 at #94 by @ysaskia 🚀
