### ISSUE TITLE
[Bug] Exports from `context="module"` are inferred as args

### ISSUE THREAD

**Issue by fallaciousreasoning** [storybookjs/addon-svelte-csf#92]
### Describe the bug

Exports from a `script` tag with `context="module"` show up as Storybook properties

### Steps to reproduce the behavior

1. Create a Svelte component with exports in a `context="module"` tag.
```svelte
<script context="module">
    export const foo = [1,2,3]
</script>
<script>
    export let myProp = "prop"
</script>

<div>{myProp} {foo.length}</div>
```

2. Create a storybook for this component
3. Both `foo` and `myProp` are visible in the properties for the component.

### Expected behavior

Exports from a `script` tag with `context="module"` do not show up as Storybook properties

**Comment by j3rem1e** [comment]
The parsing and documentation of Svelte component is not done by this plugin but is the responsibility of Storybook/svelte. You should create this issue in the storybook repo.
